### ISSUE TITLE
New PAYONE gateway

### ISSUE THREAD

**Issue by judgej** [thephpleague/omnipay-common#113]
I have a new PAYONE gateway on packagist with these three gateway drivers:

``` json
        "Payone_ShopServer",
        "Payone_ShopFrontend",
        "Payone_ShopClient",
```

It needs to go into omnipy common composer.json just so it can appear in the example application. However, this is not an "official" gateway (yet) and is not fully covered by tests. Can it still go here, or are these just "official" gateways listed?

If these are just official, then perhaps the example application needs a way for all the non-official (i.e. third party) gateways to be listed so they can be run through the example application too?

**Comment by delatbabel** [comment]
Hi Jason,

I don't believe that it's necessary or desirable for all new gateways to go into the composer.json, especially non-official gateways.  The correct thing to do with these is to add them to the README.md in the omnipay repository (thephpleague/omnipay).

**Comment by judgej** [comment]
It's the omnipay example app that makes use of these entries in `composer.json`. I'll close it here as a problem related to the example application and now `omnipay-common`.
