### ISSUE TITLE
[3.0] Pass PSR-7 Request instead collecting data from environment

### ISSUE THREAD

**Issue by aimeos** [thephpleague/omnipay-common#117]
Currently, Omnipay collects the request data from the PHP superglobals but this has two downsides:
- It doesn't work in environments where the superglobals are not populated
- Testing is complicated

To improve the situation, developers should ba able to pass a PSR-7 Request object to Omnipay which contains all data. As a fallback, Omnipay can still use the superglobals if no request object is given.

**Comment by barryvdh** [comment]
Omnipay does not use superglobals, it uses the Symfony2 http-foundation request object. See https://github.com/thephpleague/omnipay-common/blob/8217d0e8b80a97f0d1fab0e1763200636daf1c00/src/Omnipay/Common/AbstractGateway.php#L71
Only if you do not pass an object yourself, this is created from the superglobals (using `Symfony\Component\HttpFoundation\Request::createFromGlobals();` 

So you can just mock or create your own request objects for testing. And for Symfony/Laravel, use the existing request object etc.

Omnipay 3.0 in it's current state already uses PSR-7 ServerRequestInterface objects; https://github.com/thephpleague/omnipay/blob/5b8fe7f1094e81f2ff2d05239a0f0b804557d453/src/Common/Message/AbstractRequest.php#L113

**Comment by aimeos** [comment]
Thanks, didn't know that it already exists in the code for 3.0

**Comment by judgej** [comment]
@barryvdh  The `AbstractRequest` there requires a `ServerRequestInterface` to be injected in instantiation always. Is that right? The `ServerRequestInterface` object is only needed for incoming requests such as notification messages, and not at all for outgoing requests to the gateway. Similarly, when used as a `ServerRequestInterface` object, the `AbstractRequest` model does not need the `ClientInterface` passed in with the constructor.

Am I reading that correctly?

**Comment by barryvdh** [comment]
Yes,  but that was always the case. The only thing that changed was the type of object. 

And with the container version,  any message can pick their own dependencies, without needing the same abstract constructor.
