### ISSUE TITLE
Clarification on response getData method.

### ISSUE THREAD

**Issue by makasim** [thephpleague/omnipay-common#118]
The [ResponseInterface](https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/Message/ResponseInterface.php) does not define the method though the [AbstractResponse](https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/Message/AbstractResponse.php#L115) has it. 

Here are two questions:

1. The method is not part of the interface, can I rely on it, here https://github.com/Payum/OmnipayBridge/blob/master/src/Action/OffsiteCaptureAction.php#L117
2. The method return type is mixed where I expected it to be array. Is it a mistake in the doc block or it could be anything?

**Comment by makasim** [comment]
The target pay for example returns string as data: https://github.com/thephpleague/omnipay-targetpay/blob/master/src/Message/AbstractResponse.php#L24

**Comment by makasim** [comment]
and paypal returns array https://github.com/thephpleague/omnipay-paypal/blob/master/src/Message/Response.php#L16

**Comment by makasim** [comment]
I believe  there are much more gateways which return array

**Comment by judgej** [comment]
Following some examples and early drivers, I try to keep `$data` passed to a response message as an array. This keeps the parsing of the HTTP response *with* the sending of the HTTP request.

It keeps the response as simple and "dumb" as possible. It can also be useful when serialising a response (for passing around in the session) and rebuilding the response in a subsequent page.

**Comment by makasim** [comment]
@judgej thanks for the feedback.

You said guzzle http response. could you share a link to such a gateway?

**Comment by judgej** [comment]
The Sage Pay gateway does that here:

https://github.com/thephpleague/omnipay-sagepay/blob/master/src/Message/Response.php#L25

I have already copied the parsing of the result into an array to the request class here:

https://github.com/thephpleague/omnipay-sagepay/blob/master/src/Message/AbstractRequest.php#L157

but I've left the parsing in the response for now, in case anyone is relying on it.
