### ISSUE TITLE
[3.0] Plan of action / Upgrade path

### ISSUE THREAD

**Issue by barryvdh** [thephpleague/omnipay-common#128]
I think we tackled most issues for Omnipay 3, so if no one has any breaking changes, I suggest we start to convert an actual gateway.

Biggest changes for upgrading:
 - Different namespace
 - Psr-7 client, methods changed a bit.
 - Psr-7 request/responses, different signatures.
 - Amount is now always an object, also needs to return an object from the PurchaseResponses
 - Creditcard object is split out to separate Customer object
 - Pre-defined onstants for Response statuses
- ..?

We can convert a few, but we should probably try to let the community fix the rest..

**Comment by delatbabel** [comment]
OK is there a HOWTO on upgrading a gateway somewhere?  I probably have time this weekend to work on one of the simpler REST based gateways that I have (e.g. PIN, Stripe, FatZebra) if I can get a HOWTO.

**Comment by barryvdh** [comment]
Yeah I was trying PayPal yesterday as example, will post result when finished

**Comment by barryvdh** [comment]
Here are my findings from Paypal: https://github.com/thephpleague/omnipay-paypal/pull/152
 
(I did not actually test this, just made the tests work)

**Comment by barryvdh** [comment]
So, any feedback?

**Comment by delatbabel** [comment]
Sorry I've been away for a bit and haven't had time to follow this up.  Is there a set of instructions I can use to try Omnipay 3.0 common + paypal?
