### ISSUE TITLE
AbstractRequest::validate() errors on fields that are set but evaluate to empty()

### ISSUE THREAD

**Issue by judgej** [thephpleague/omnipay-common#13]
Similar to Issue #3, Helcim allows zero amounts to be submitted for authorisation (so long the correct flag is set).

Now, the AbstractRequest uses `empty()` to check if a field is set. This will raise an error on any field that is zero, "false", "", etc. and that includes an amount of "0.00". I strongly suspect that `empty()` is not the right check for this, since "0.00" is very much a set field.

The validation method can be overridden, which I suspect is the intention (not so easy with the CreditCard validation, which is another subject to tackle) but reporting a set field as not set is unexpected behaviour, I believe.

I'll not suggest an alternative until I understand a bit more about how this validation is used across the drivers (it could be that *everyone* overrides it).

**Comment by kayladnls** [comment]
@markdegrootnl feel free to make a PR for that. Sounds good.

**Comment by judgej** [comment]
This would fail on numeric value 0 or 0.0. They would both be detected as missing parameters.

Are we still just looking at replacing `empty()` with `! isset()`?

**Comment by delatbabel** [comment]
Note that replacing empty() with ! isset() is sufficient now because the if ($amount) in getAmount() has already been fixed to if ($amount !== null).  I have submitted an updated PR #76 for this and will merge that in place of #64

**Comment by delatbabel** [comment]
Merged #76
