### ISSUE TITLE
Fix abandoned gruzzle package

### ISSUE THREAD

**Issue by psihius** [thephpleague/omnipay-common#131]
This is what composer gives us as a fat warning:
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

Need to update the dependency to a working one.

**Comment by nestormata** [comment]
👍 I second the request

**Comment by delatbabel** [comment]
This is a FAQ and part of the Omnipay 3.0 change list.  There are too many breaking changes to backport this to Omnipay 2.0.
