### ISSUE TITLE
Omnipay\Common\AbstractGateway::createRequest it get gateways params and send it to resolver class.

### ISSUE THREAD

**Issue by parfumix** [thephpleague/omnipay-common#132]
Now Omnipay\Common\AbstractGateway::createRequest it got gateways params and send it to resolver class using array_replace.

Now:: if i have setAppKey function i have to declare that function in Gateway and in resolver class for example purchaseRequest which forces me to dublicate code.

Solution: $obj->initialize( $this, $parameters ) and declare to Omnipay\Common\Message\Omnipay\Common\Message -> set / get Gateway..

Thank you.

**Comment by barryvdh** [comment]
Sorry, I don't understand what you're trying to say. Can you provide an example?

**Comment by delatbabel** [comment]
> if i have setAppKey function i have to declare that function in Gateway and in resolver class for example purchaseRequest which forces me to dublicate code.

Yes I think that's known expected behaviour.  If your purchaseRequest doesn't need the appKey parameter then you omit that function from the purchaseRequest.  This prevents message classes from attempting to handle parameters that they don't need or use.
