### ISSUE TITLE
update "guzzle/guzzle" to 6 version

### ISSUE THREAD

**Issue by videni** [thephpleague/omnipay-common#133]
```
 "guzzle/guzzle": "~3.9",
  "symfony/http-foundation": "~2.1|~3.0"
```

because "guzzle/guzzle" uses  "symfony/event-dispatcher": "~2.1", when we use this package with symfony 3, which will install  "symfony/event-dispatcher" twice.

**Comment by delatbabel** [comment]
This will not be done in the current release.  It is a FAQ.  It will happen in the 3.0 release.
