### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by mozgbrasil** [thephpleague/omnipay-common#139]
Hello

Good morning my friends

-

According to images

-

We see that the following alert is displayed in the library installation using the composer

"Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."

-

Access the following link

https://packagist.org/search/?q=guzzle

We see that this "guzzle/guzzle" package is actually abandoned, and the "guzzlehttp/guzzle" library should be used

-

![captura de tela de 2017-01-27 10-56-53](https://cloud.githubusercontent.com/assets/17202780/22371651/5fa9cc56-e47f-11e6-8918-395ada24473a.png)

**Comment by Bulmer** [comment]
+1 for this update. Any timeframe for this? This seems to be the only package in my project that still uses guzzle/guzzle.

**Comment by delatbabel** [comment]
This is a FAQ and will not be done for Omnipay 2.0, it's on the 3.0 list.

**Comment by Bulmer** [comment]
Thanks delatbabel, but could you explain what an "FAQ" is? Also is there any risk of broken payment transactions during this transition between v2 and v3?
