### ISSUE TITLE
v2.5.2 composer.json still requrie guzzle/guzzle

### ISSUE THREAD

**Issue by ccaa7530** [thephpleague/omnipay-common#157]
My project composer.json require "omnipay/paypal": "2.6.3"
and omnipay/paypal require "omnipay/common": "~2.0"
then composer install/update
**`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`**

omnipay/common .composer.json need to update,right?
```
    "require": {
        "php": ">=5.3.2",
        "guzzle/guzzle": "~3.9",
        "symfony/http-foundation": "~2.1|~3.0"
    },
```
Download omnipay-common v2.5.2 source code , .composer.json the same problem

Please help solve it, thank you.

**Comment by barryvdh** [comment]
Will be in v3
