### ISSUE TITLE
Install via composer problems using omnipay with Drupal

### ISSUE THREAD

**Issue by NewZeal** [thephpleague/omnipay-common#164]
Hi there.  I'm attempting to install a Drupal module which uses omnipay common library and there are problems surrounding some symfony components, specfically symfony/event-dispatcher and symfony/http-foundation.

https://www.drupal.org/project/commerce_dps/issues/2934276

I'm wondering if you can shed any light on how this might be resolved.  Thanks.

**Comment by jblotus** [comment]
+1 would like to install newest version of EventDispatcher but old version old guzzle is preventing this

**Comment by jblotus** [comment]
kind of address by https://github.com/thephpleague/omnipay-common/issues/157

any workarounds maybe?

**Comment by jblotus** [comment]
sorry - just noticed the readme has explicit answer to this.

**Comment by NewZeal** [comment]
Which readme has the answer and what is the answer? Thanks.

**Comment by jblotus** [comment]
https://github.com/thephpleague/omnipay/blob/master/README.md

Basically you can try to install an older version of symfony/event-dispatcher

but your mileage may vary depending on what other packages you need

**Comment by NewZeal** [comment]
Yes, found it, thanks.   I'm pretty much bound by other dependencies.  I guess I can wait until the fix happens:

```
If you are using Symfony 3 (or Symfony 3 components), please note that Omnipay 2.x still relies on Guzzle3, which in turn depends on symfony/event-dispatcher 2.x. This conflicts with Symfony 3 (standard install), so cannot be installed. Development for Omnipay 3.x is still in progress at the moment.

If you are just using the Symfony 3 components (eg. stand-alone or Silex/Laravel etc), you could try to force the install of symfony/event-dispatcher:^2.8, which is compatible with both Symfony 3 components and Guzzle 3.
```

**Comment by delatbabel** [comment]
Yes, this will need to wait until the Omnipay 3.0 release.
