### ISSUE TITLE
[2.5.1] What happened to the Currency

### ISSUE THREAD

**Issue by dilab** [thephpleague/omnipay-common#167]
There used to be a long list of supported currency code:
https://github.com/thephpleague/omnipay-common/blob/2.5/src/Omnipay/Common/Currency.php#L84

But it was reduced to a small list:
https://github.com/thephpleague/omnipay-common/blob/v2.5.1/src/Omnipay/Common/Currency.php#L84

What happened?

**Comment by collizo4sky** [comment]
I also want to know.

**Comment by barryvdh** [comment]
It's the other way around, those were added in 2.5.2. The 2.5 branch is the latest branch for 2.5.x

**Comment by dilab** [comment]
@barryvdh 
this is 2.5.2: https://github.com/thephpleague/omnipay-common/blob/2.5.2/src/Omnipay/Common/Currency.php#L84

this is 2.5: https://github.com/thephpleague/omnipay-common/blob/2.5/src/Omnipay/Common/Currency.php#L85

Currencies are removed from 2.5.2
