### ISSUE TITLE
Loading all gateways, but omnipay/common version incorrect

### ISSUE THREAD

**Issue by dazza041** [thephpleague/omnipay-common#176]
Not sure if this has been covered in a previous thread but, is there a reason when loading in all gateways - through "omnipay/omnipay" - the versions for omnipay/common and omnipay/sagepay are not at there most recent (2.3.4 and 2.4.0).

We've replaced "omnipay/omnipay" with: `"omnipay/sagepay": "~2.0"` and now the versions of common (2.5.2) and SagePay (2.5.1) are massively updated.

Ideally, we'd like to pull in all gateways as our Transaction handling setup allows clients to switch payment types without us, or other developers, needing to do very much. But obviously we can't do that if versioning of the gateways is going to be inconsistent.

**Comment by barryvdh** [comment]
Pulling all gateways is not supported.
