### ISSUE TITLE
2.x Guzzle PEM File out of date

### ISSUE THREAD

**Issue by funkflute** [thephpleague/omnipay-common#193]
The version of Guzzle (3) used in 2.x has an out of date PEM file, so my SSL connections to our CC proc. started failing... (curl error 60)... other than upgrading to omnipay 3.x, (which is not a quick solution) is there a fix for this, or a way to get omnipay to get guzzle to use a different cainfo cert?

I have tried updating curl.cainfo in my php.ini to no effect, and looks like Guzzle 3 can only change the PEM programmatically (ClientInterface::setSslVerification), not through system settings.

**Comment by barryvdh** [comment]
Upgrading to 3.x should be a quick solution, for end users there should be very little changes.

**Comment by judgej** [comment]
I'll close this as no longer relevant, since support for 2.x is now just a recommendation to upgrade to 3.x - hope that's not jumping the gun.
