### ISSUE TITLE
composer missing dep: php-http/client-implementation ^1

### ISSUE THREAD

**Issue by puggan** [thephpleague/omnipay-common#197]
Composer complains about: 
  Problem 1
    - omnipay/common v3.0.2 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0.1 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0.0 requires php-http/client-implementation ^1 -> no matching package found.

**Comment by judgej** [comment]
You need to make sure a http client implementation is installed. That means Guzzle, or any of a multitude of others that support the Httplug interface. Omnipay no longer requires one specific http client.

**Comment by puggan** [comment]
guzzle was already installed, as it was required by the earlier version of omnipay/common.

So is it a bug in composer, that make it unable to resolve the dependencies?

**Comment by barryvdh** [comment]
You also need the adapter, or the `league/omnipay` base package. See http://omnipay.thephpleague.com/installation/
