### ISSUE TITLE
Migrate to php-http/client-imlementation ^2

### ISSUE THREAD

**Issue by hacktivista** [thephpleague/omnipay-common#206]
Is there interest in upgrading to the next php-http version? @barryvdh

**Comment by barryvdh** [comment]
I don't think we need to change anything, right? Only the default guzzle6 adapter can be changed to v2?

**Comment by barryvdh** [comment]
See https://github.com/thephpleague/omnipay/pull/556

**Comment by hacktivista** [comment]
Yes... I missed the point here. I've had a difficult time trying to fit all pieces of this httplug / PSR mixture.
