### ISSUE TITLE
Call to protected method Omnipay\Common\AbstractGateway::setParameter()

### ISSUE THREAD

**Issue by mattsah** [thephpleague/omnipay-common#217]
In 3.0.2 setParameter is a public method on the AbstractGateway -- in 3.0.3 this method appears to be protected via ParametersTrait.

This breaks backwards compatibility.

**Comment by kevin-jones** [comment]
Any update on this? We've had to lock our projects to 3.0.2 now and cannot upgrade until this is resolved.

**Comment by tobelyan** [comment]
Also facing this issue. Locked to version 3.0.2

**Comment by barryvdh** [comment]
I think this should solve it: https://github.com/thephpleague/omnipay-common/pull/220

**Comment by barryvdh** [comment]
Tagged
