### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by makroxyz** [thephpleague/omnipay-common#227]
please update for using Laravel 8

**Comment by siarheipashkevich** [comment]
@barryvdh please update packages for using laravel 8. Right now I can't update guzzlehttp/guzzle to ^7.0.1.

**Comment by stu177** [comment]
Any update on this?

As a workaround, I've managed to get it working by requiring `php-http/guzzle7-adapter` in my `composer.json`.

**Comment by barryvdh** [comment]
Should already be fixed.
