### ISSUE TITLE
Add getUserMessage() to the response object

### ISSUE THREAD

**Issue by eileenmcnaughton** [thephpleague/omnipay-common#23]
This allows for situations where the displayable message might differ from the raw message or the processor returns more than one type of message e.g 'failed transaction' for user & 'fraudster alert' for the admin

**Comment by judgej** [comment]
PAYONE has a return field called `customerMessage`. It is translated to the spoken language that has been requested for the API, and is safe to put in front of end users. I can see this happening for more gateways over time.

**Comment by delatbabel** [comment]
OK so any objections to me merging this?

**Comment by delatbabel** [comment]
By "this" I specifically mean PR #22

**Comment by delatbabel** [comment]
OK I can see it got closed. Please ignore. I will close the issue and if someone wants to raise it again then they can. Otherwise maybe it can be a v3.0 target.

**Comment by eileenmcnaughton** [comment]
I can't seem to re-open it myself

**Comment by delatbabel** [comment]
If it's a PR and it's been closed, it can't be re-opened. You will have to submit it again. I can reopen the issue if you want.

**Comment by eileenmcnaughton** [comment]
Hmm - I brought the PR back to life but it was failing tests - pretty sure it was not adding the fn to the right place so let's leave it

**Comment by delatbabel** [comment]
Noted, thanks for your efforts anyway.
