### ISSUE TITLE
composer install last package - v3.1.0

### ISSUE THREAD

**Issue by npulidom** [thephpleague/omnipay-common#234]
Hello! It seems that the last packagist version `v3.1.0` doesn't include commit [d0970b8](https://github.com/thephpleague/omnipay-common/commit/d0970b828bc47e193c1125a9b0a4a31dffaa42a5). The Symfony deprecation exception it's still present on this version.
`The "Symfony\Component\HttpFoundation\RedirectResponse::create()" method is deprecated, use "new Symfony\Component\HttpFoundation\RedirectResponse()" instead.' /var/www/vendor/symfony/deprecation-contracts/function.php [25]`

Screenshot
https://pasteboard.co/Jy4M2uh.png

**Comment by barryvdh** [comment]
Tagged
