### ISSUE TITLE
Is there any standard way to choose gateway's environment consistently?

### ISSUE THREAD

**Issue by devnix** [thephpleague/omnipay-common#235]
I'm trying to understand how to send the purchase to the sandbox environment in PayPal Express and Redsys gateways, but I'm not finding a specific way to specify that I'll want to go to a sandbox environment (I will need to implement a couple more of gateways).

I've found a `setEnvironment` method in some gateways, and others have a custom named parameter, and I'm unsure about how to proceed.

**Comment by barryvdh** [comment]
`testMode` is the default parameter. See https://omnipay.thephpleague.com/gateways/configuring/

**Comment by devnix** [comment]
So it's not gateway dependent? (Sorry if I'm making dumb questions :D)

**Comment by barryvdh** [comment]
It depends on the gateway to implement it correctly. But if a sandbox is possible, it should use that parameter.

**Comment by devnix** [comment]
Ok, thank you!
