### ISSUE TITLE
Release that supports PHP 8

### ISSUE THREAD

**Issue by ejunker** [thephpleague/omnipay-common#246]
I see that master has updated composer.json to support PHP 8. But the latest version at the moment 3.0.5 does not support PHP 8. Please tag a new release so that it has PHP 8 support.

**Comment by toooni** [comment]
@barryvdh Is there a chance a new release will be dropped soon? 
As I see it `phpro/grumphp` must be bumped to `^1.0` to support PHP8. For this to happen we need to have this merged as well: https://github.com/thephpleague/omnipay-tests/pull/16

**Comment by alexw23** [comment]
Any update on this one? Will a release soon be tagged?

**Comment by emielmolenaar** [comment]
This would be great.

**Comment by emielmolenaar** [comment]
https://github.com/thephpleague/omnipay/releases/tag/v3.2.0 🥳

**Comment by barryvdh** [comment]
Yes it's tagged. I've removed Grumphp and had to bump the test suite to PHPUnit 9 (with typehints and removal of deprecated things), so also dropped PHP 7.2. But that's not supported anymore anyway.

**Comment by alexw23** [comment]
This is awesome, thanks @barryvdh 🎉 

I suppose we also need to wait for each individual driver (omnipay-stripe etc) to bump up?

**Comment by barryvdh** [comment]
Yeah but you can make a PR by bumping the PHP version in composer, the github actions matrix and update the testsuite to use omnipay/tests v4 instead of v3.

**Comment by emielmolenaar** [comment]
> Yeah but you can make a PR by bumping the PHP version in composer, the github actions matrix and update the testsuite to use omnipay/tests v4 instead of v3.

Thanks! I am creating a PR for omnipay-mollie. Did I miss something, or is version 4 of omnipay/tests not tagged yet?

**Comment by barryvdh** [comment]
Correct, is was dev only. But it's tagged now
