### ISSUE TITLE
Create new release with Symfony 7 support

### ISSUE THREAD

**Issue by Chris53897** [thephpleague/omnipay-common#267]
Can you please add a new tag, after the ci is green again with
https://github.com/thephpleague/omnipay-common/pull/266 ?

My goal is to have symfony 7 support in Payum.
https://github.com/Payum/OmnipayV3Bridge/pull/16

**Comment by barryvdh** [comment]
https://github.com/thephpleague/omnipay-common/releases/tag/v3.3.0
Thanks!

**Comment by Chris53897** [comment]
thanks @barryvdh
