### ISSUE TITLE
MessageFactoryDiscovery of php-http/discovery is depricated now 

### ISSUE THREAD

**Issue by Axent96** [thephpleague/omnipay-common#268]
\Omnipay\Common\Http\Client line 8 =>
please use Psr17FactoryDiscovery instead of the [also deprecated](https://github.com/php-http/discovery/blob/1.x/src/MessageFactoryDiscovery.php#L13) MessageFactoryDiscovery

**Comment by FaboPT** [comment]
https://github.com/thephpleague/omnipay-common/pull/269
