### ISSUE TITLE
Does AbstractRequest->getCurrencyDecimalFactor() need to be private?

### ISSUE THREAD

**Issue by cfreear** [thephpleague/omnipay-common#27]
I'm currently implementing the application_fee parameter in [thephpleague/omnipay-stripe](https://github.com/thephpleague/omnipay-stripe) and have added a `getApplicationFeeInteger()` to mirror `getAmountInteger()` but it makes use of `getCurrencyDecimalFactor()` a private method of [`Omnipay\Common\Message\AbstractRequest`](https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/Message/AbstractRequest.php#L214) so I'm having to duplicate the code in Stripe's `AuthorizeRequest`.

Is there any reason this need's to be private or am I better off with my implementation?

**Comment by kayladnls** [comment]
No, that function can be protected, so that descendant classes have access also.

**Comment by hugohenrique** [comment]
Any news? Already can be closed?

**Comment by judgej** [comment]
There is a public function `getCurrencyDecimalPlaces()` now that replaces `getCurrencyDecimalFactor()`.

I'll close this issue as it's no longer directly applicable.
