### ISSUE TITLE
Tag a release? It would be nice to see last merges released

### ISSUE THREAD

**Issue by eileenmcnaughton** [thephpleague/omnipay-common#270]
There was a composer update 6 months ago - could we get that tagged?

**Comment by barryvdh** [comment]
What do you mean? The latest commit is tagged; https://github.com/thephpleague/omnipay-common/releases/tag/v3.3.0

**Comment by eileenmcnaughton** [comment]
Yeah sorry - you are right - I realise I was doing something wrong!!!
