### ISSUE TITLE
Unexpected exception for payment forms with uploaded file

### ISSUE THREAD

**Issue by frederikbosch** [thephpleague/omnipay-common#30]
When using Omnipay on pages that contains file uploads, a Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException is thrown when you have moved the uploaded file.

More specifically: the error is generated on [this line](https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/AbstractGateway.php#L238). The createFromGlobals uses $_FILES which in turn contains a reference to a file that has been moved. This results in the following stack.

```json
{
    "exception": {
        "class": "Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException",
        "message": "The file \"/tmp/phpNXhFUC\" does not exist",
        "file": "/path-to-project/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/File/File.php:41",
        "trace": [
            "/path-to-project/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/File/UploadedFile.php:100",
            "/path-to-project/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/FileBag.php:99",
            "/path-to-project/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/FileBag.php:62",
            "/path-to-project/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/FileBag.php:73",
            "/path-to-project/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/FileBag.php:48",
            "/path-to-project/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/FileBag.php:37",
            "/path-to-project/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Request.php:256",
            "/path-to-project/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Request.php:232",
            "/path-to-project/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Request.php:1918",
            "/path-to-project/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Request.php:295",
            "/path-to-project/vendor/omnipay/common/src/Omnipay/Common/AbstractGateway.php:238",
            "/path-to-project/vendor/omnipay/common/src/Omnipay/Common/AbstractGateway.php:47",
            [... project code ...]
            "/path-to-project/public/index.php:3"
        ]
    }
}
```

**Comment by kayladnls** [comment]
I'm thinking that the line numbers have changed? 47 is a comment and 238 is a closing brace. 

What version of Omnipay are you using? It shouldn't be touching files. I'll look into this right way.

**Comment by frederikbosch** [comment]
Omnipay is not touching files. It is Symfony HttpRequest that is expecting $_FILES to contain files that exists (in the temp dir where php puts those files). My workaround now is to copy files, instead of moving.

So Omnipay should not rely on Symfony::createFromGlobals, or it should pass others parameters.

The line I am referring has been changed indeed. It is now the last method of the AbstractGateway.

Since I am sending the message from my phone, I do not have the opportunity to link to resources. Nonetheless, I hope it is more clear now.

**Comment by kayladnls** [comment]
Yes, thank you. I found it. 

From what I can see, createFromGlobals doesn't do anything to unset/move the files, so I'm not sure why it's Interfering with your later attempt to access the files. 

Have you eliminated any other options that may be interferring with the request, other than Omnipay?

**Comment by frederikbosch** [comment]
HttpFoundation is not doing anything with files. But it is requiring/counting on the files being present. When it is not, it throws an exception.

However, you pointed out an important circumstance: I am initializing Omnipay after I moved the files. This is important. If I would have initialized Omnipay before moving the files, there would be no problem.

Looking at the bug again: why is Omnipay counting on $_FILES anyway? Admitted: I might reconsider the moment of initialization (properly injecting my dependency). But a payment library should not have a dependency towards a superglobal like $_FILES.

**Comment by frederikbosch** [comment]
@kayladnls Just created a PR for this (by editing the file on github). It removes the dependency towards $_FILES. To be honest: I do not know if it solves my problem. But I guess it does. Will let you know today.

**Comment by frederikbosch** [comment]
Update: I also see that some tests are failing because older versions of Symfony/HttpFoundation do not have this method setFactory.

@kayladnls Maybe it is better to close this issue. Symfony/HttpFoundation seems to be a deep dependency of Omnipay. Any modification will raise other issues. But I guess this bug proves there is a downside to have such a deep dependency.

**Comment by kayladnls** [comment]
@frederikbosch in thinking I can swap out `createFromGlobals()` in favour of `create()` and pass an empty array in place of $_FILES. 

I'll play with that shortly.
