### ISSUE TITLE
Clarify getTransactionId vs getTransactionReference

### ISSUE THREAD

**Issue by eileenmcnaughton** [thephpleague/omnipay-common#31]
I'm just wanting to check I'm right before I try to change my gateway to follow this - I believe that

getTransactionId 
should return the ID generated by the client site (ie. the commerce site or other site that uses a payment gateway service).

getTransactionRef
should return a gateway generated unique ID. (e.g paypal reference)

I'm focussing on completePurchaseRequest at the moment but I think this should be the standard pattern are you able to confirm?

**Comment by judgej** [comment]
Yes, getTransactionReference() is the ID generated by the gateway. The transaction ID is generated, as you say, by the merchant site/commerce site/your site.

**Comment by judgej** [comment]
I think this answer has been open long enough without any arguments against it :-)
