### ISSUE TITLE
why don't change guzzle/guzzle to guzzlehttp/guzzle

### ISSUE THREAD

**Issue by argb** [thephpleague/omnipay-common#33]
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by TiGR** [comment]
I was about to make pull request, but contributing guidelines state that contributors should not touch composer.json. So, how can we fix this?

Just in case it was not clear from @argb comment: composer shows several warnings in any project dependant on omnipay-common.

**Comment by colinodell** [comment]
+1

`guzzle/http` is abandoned and hasn't been updated since August:

![image](https://cloud.githubusercontent.com/assets/202034/6732043/9e759bb8-ce1f-11e4-904f-9b78430e6f7f.png)

`guzzle/guzzle` has one newer release but is deprecated in favor of Guzzle 5 (`guzzlehttp/guzzle`):

![image](https://cloud.githubusercontent.com/assets/202034/6732073/c3d5bb4a-ce1f-11e4-9f3c-085e9df82299.png)

If it's feasible, I think jumping to Guzzle 5 would be best.  If not, perhaps just change to `guzzle/guzzle` to remove the Composer warnings and provide access to that latest patch version?

**Comment by kayladnls** [comment]
Guzzle 5 would require a bit of a rewrite, and is on the books for V3 of Omnipay

I can merge the PR for guzzle/guzzle, to stop the errors, though.

**Comment by TiGR** [comment]
@kayladnls, ok, made it.

**Comment by bweston92** [comment]
@kayladnls can I recommend a HTTP transport layer is written? So it isn't hard coded to any third party package? `TransporterInterface` and `GuzzleTransporter` implementation? Saves a whole re-write every time.

**Comment by elliot** [comment]
Why reinvent the wheel?

Ideally the HTTP transport interface should be converted to PSR-7 once it is released. Guzzle has a [PSR-7 branch](https://github.com/guzzle/psr7) in the works at the moment. That way the transport could be switched out for any other implementation, or a simple cURL based one provided if need be.

**Comment by bweston92** [comment]
@elliot ermm re-inventing the wheel?

You should have adapter classes around external dependencies anyway, mainly so your tests use the adapter and secondly so when a package changes you can update the code accordingly, right now this is all hard coded to Guzzle and even worse a legacy version.

**Comment by TiGR** [comment]
Ok, PR now passes tests in all configurations.

**Comment by argb** [comment]
I am waiting all the time,if don't fix the problem,I have to give up omnipay,because other pacakges depends on  Guzzle 5,so if i use omnipay,i have to introduce two version Guzzle.

**Comment by argb** [comment]
Guzzle version 3. This is somewhat maintained, but upgrading to Guzzle 5 is strongly recommended.

**Comment by kayladnls** [comment]
That's the plan with the next major version of Omnipay.
