### ISSUE TITLE
Make your gateway official

### ISSUE THREAD

**Issue by andreas22** [thephpleague/omnipay-common#35]
Hi,

I have built a gateway for Fasapay (https://github.com/andreas22/omnipay-fasapay) and I would like to make it official. In the documentation it says  "please open a pull request on the omnipay/common package". Is not very clear what exactly needs to be done, any instructions would be very helpful.

Thanks

**Comment by kayladnls** [comment]
Andreas, 

You actually need to make a PR to https://github.com/thephpleague/omnipay/blob/master/README.md in the omnipay repo. Add your gateway to the list of gateways, and then make a PR and I will merge it in. 

Thanks!

**Comment by andreas22** [comment]
Ok, now is clear so you need also to update the documentation as well at http://omnipay.thephpleague.com/gateways/build-your-own/ 

Thanks
