### ISSUE TITLE
Protected to public method

### ISSUE THREAD

**Issue by bryglen** [thephpleague/omnipay-common#44]
I am creating a wrapper more flexible and dynamically and something like this

```php
$this->_gateway = Omnipay::create($this->name);
foreach ($this->parameters as $key => $value) {
      $this->_gateway->setParameter($key, $value);
}
```

can we change the protected into public? since they are getter and setter methods

https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/AbstractGateway.php#L139

**Comment by barryvdh** [comment]
What do you need, all parameters? Can't you use `getParameters()` ?

**Comment by bryglen** [comment]
I am trying to dynamically setting a parameter. so `getParameters()` won't do the job because I am not creating a class in each gateway but rather calling a factory method and dynamically set a parameters

**Comment by barryvdh** [comment]
And `initialize($this->parameters)`?

**Comment by bryglen** [comment]
`initialize` can help but that method will call the default parameter over again. you can't have a flexibility to override a single setter method

**Comment by bryglen** [comment]
is it valid reason? if yes I can make PR for this.

**Comment by kayladnls** [comment]
I'm okay with making the setter function public. Create a PR and I will merge it. @bryglen

**Comment by bryglen** [comment]
what's the status here? my PR is still pending request
