### ISSUE TITLE
Possible class loading issue for supported gateways

### ISSUE THREAD

**Issue by monkeyphp** [thephpleague/omnipay-common#59]
I was attempting to using Omnipay (with Payum) and the Realex gateway developed by - https://github.com/coatesap/omnipay-realex

For some reason, I continued to receive `Fatal error: Uncaught exception 'Payum\Core\Exception\LogicException' with message 'Given type Realex_Remote is not supported. Try one of supported types: .' in /mnt/project/farmison/vendor/payum/omnipay-bridge/src/OmnipayDirectGatewayFactory.php on line 71`

Tracking through the call stack, it appears that here https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/GatewayFactory.php#L81 a check is made using `class_exists` - but no classes were being found even though the Realex gateway is listed here
https://github.com/thephpleague/omnipay-common/blob/master/composer.json#L88

Upon var_dumping the $gateway and $class in the GatewayFactory::find method - it appears to be using 
`string 'Realex Remote =>  \Omnipay\Realex Remote\Gateway' (length=48)` which doesnt appear to be a valid FQDN and once I had underscored the space in composer.json https://github.com/thephpleague/omnipay-common/blob/master/composer.json#L88 the class now loads.

**Comment by kayladnls** [comment]
Yes, I believe you're right. It's likely doing the same for any of the gateways with a string in their name, as well as SecPay. I've marked this as a bug to be fixed. I'll ping back here once it's taken care of.

**Comment by kayladnls** [comment]
After looking into this further, those gateways shouldn't have been listed in `omnipay-common` in the first place. I'm not sure how that effects things in relation to Payum, as I have no first hand experience with it, but only gateways with the Omnipay namespace are accessible through `Omnipay::find()`
