### ISSUE TITLE
Compatibility with Symfony 3.0

### ISSUE THREAD

**Issue by mkrauser** [thephpleague/omnipay-common#65]
currently omnipay requires 

```"symfony/http-foundation": "~2.1"```

which makes it currently unusable in Symfony 3.0 projects. 
Symfony 3.0 was released yesterday.

Thank you for looking into this.

**Comment by mkrauser** [comment]
Also, guzzle 3.9, which is also required by omnipay-common required the symfony event-dispatcher 2.x which results in the same problem

**Comment by frederikbosch** [comment]
And I would recommend to change the current dependency into `"symfony/http-foundation": "~2.7.0"`. With http foundation 2.8.0 you receive `symfony/polyfill-php54` for free and as PHP 5.6 user I do not like to see such a dependency entering my project suite.

**Comment by barryvdh** [comment]
See #67

**Comment by wimpog** [comment]
Hi Barry,
Could you please tell me the overall state of OmniPay version 3. 
I see that you've been replacing Guzzle with PHP-HTTP.
Is there a reason you chose not to use Guzzle 6?
What is left to be done in omnipay-common?
What's the difference between branch 3.0 and 3.0-simple? Do they have different purposes? I see one uses Guzzle, and the other one does not.
I see you require PHP 5.6, or 7: "php": "^5.6|^7". I use php 5.5.29, would it be ok with 5.5?
Thanks,

**Comment by barryvdh** [comment]
Php 5.5  is not supported anymore. 
Guzzle will be de default adapter for Php http,  just not tied to it. 
Overall state is that this should be able to release not to far from now,  while 3.0 branch can be pushed back as 4.0

**Comment by wimpog** [comment]
What's the difference between branch 3.0 and 3.0-simple? Do they have different purposes? I see one uses Guzzle, and the other one does not.

**Comment by barryvdh** [comment]
3.0 is simpler. Both use psr7 and both can support guzzle.

**Comment by barryvdh** [comment]
Sorry, 3.0-simple is simpler. It's an intermediate version for easier upgrading.

**Comment by wimpog** [comment]
Barry,
Will version 3 continue with Guzzle or PHP-HTTP?
THanks
