### ISSUE TITLE
LGTM

### ISSUE THREAD

**Issue by delatbabel** [thephpleague/omnipay-common#75]
Can we get some of the older PRs on this either merged or moved aside?  Some have been hanging around for 2 years.

PRs that just add test coverage or docblocks should be a candidate for merging if they don't break anything.

**Comment by judgej** [comment]
I think a lot have been moved to discussions in other areas - 3.0 threads, specific gateways etc. Personally, I'll work through what I can over the next few weeks, but it will likely just be an hour here and there.

**Comment by delatbabel** [comment]
OK, if you want me to go through a few then let me know

**Comment by judgej** [comment]
Oh yeah - don't hold back :-)

**Comment by delatbabel** [comment]
I have completed merging those that are trivial changes -- adding the extra currency, adding comments/docblocks and adding test cases. The remainder of the outstanding PRs require some discussion or feedback.
