### ISSUE TITLE
Unable to use Omnipay with laravel 5.2

### ISSUE THREAD

**Issue by GopaThemes** [thephpleague/omnipay-common#78]
I am developing an eCommerce website using Laravel 5.2 and trying to install Omipay ( payment processing library ) via composer. But composer throwing the following errors when I tried.

`Your requirements could not be resolved to an installable set of packages.

Problem 1
- Conclusion: don't install omnipay/omnipay 2.3.2
- Conclusion: don't install omnipay/omnipay v2.3.1
- Conclusion: remove symfony/http-foundation v3.0.1
- Installation request for omnipay/omnipay ^2.3 -> satisfiable by omnipay/omnipay[2.3.2, v2.3.0, v2.3.1].
- Conclusion: don't install symfony/http-foundation v3.0.1
- omnipay/omnipay v2.3.0 requires omnipay/common ~2.3.0 -> satisfiable by omnipay/common[2.3.2, v2.3.0, v2.3.1, v2.3.3, v2.3.4].
- omnipay/common 2.3.2 requires symfony/http-foundation ~2.1 -> satisfiable by symfony/http-foundation[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].`

Please suggest me the solution how could I fix that?

Thanks

**Comment by barryvdh** [comment]
Sorry, Omnipay doesn't yet work on Symfony 3

**Comment by GopaThemes** [comment]
@barryvdh any suggestion to make it work?

**Comment by barryvdh** [comment]
No, sorry

**Comment by delatbabel** [comment]
I would suggest that you develop your code based on Laravel 5.1.  That has long term support, and Laravel 5.2 does not. Once a version of Omnipay is released that supports Laravel 5.2+ and Symfony 3 then you can switch your code to a later version of Laravel -- either 5.2 or whatever other later version has long term support.

If you're building something like an e-commerce website then I would stick with a LTS version of Laravel. You don't want to be messing with the internal workings of your code every time a new idea pops into Taylor's head, and he does have a reputation for breaking a whole heap of stuff between minor and sometimes even point releases.

**Comment by ejunker** [comment]
Laravel 5.2 requires `"symfony/http-foundation": "2.8.*|3.0.*"` so it should be able to install version `2.8.*` and work.

**Comment by upnorthal** [comment]
For a Laravel 5.2 install, can I just update Laravel's composer.json and set the line to read
"symfony/http-foundation": "2.8.*" - meaning this will force Laravel to run under symfony 2 ?
