### ISSUE TITLE
New MasterCard "2" series BIN range support?

### ISSUE THREAD

**Issue by pixelchutes** [thephpleague/omnipay-common#87]
It is my understanding that starting October 14, 2016 systems will need to begin accepting MasterCards starting with a `2`. _(This also includes any supported gateway providers.)_

Sourced from [wikipedia](https://en.wikipedia.org/wiki/Bank_card_number) and [this post](http://www.foxycart.com/blog/upcoming-mastercard-changes-and-what-you-should-know):
> On November 3, 2014, MasterCard announced that they were introducing a new series of BIN ranges that begin with a “2” (222100–272099). The “2” series BINs will be processed the same as the “51–55” series BINs are today. **They will become active 14 October 2016.**

I checked against `omnipay/common (v2.5.0)` and it seems to add this support, an update would be required to the `$supported_cards` regexes in [CreditCard.php](https://github.com/thephpleague/omnipay-common/blob/550138529e850143af7a87eab8cfe16e72a2f768/src/Omnipay/Common/CreditCard.php#L122)

```php
    protected $supported_cards = array(
        self::BRAND_MASTERCARD => '/^(5[1-5]\d{4}|677189)\d{10}$/', // Regex to be updated?
        // ...
    );
```

Any reason this support should not be added to `omnipay/common`  ahead of the Oct 2016 deadline?

**Comment by delatbabel** [comment]
There is no reason that it should not be added.  A PR would be appreciated.

**Comment by pixelchutes** [comment]
Happy to!
