### ISSUE TITLE
Driver setter imposing limits causes test case breakage.

### ISSUE THREAD

**Issue by rquadling** [thephpleague/omnipay-common#92]
Hi.

What is the preferred/expected way to handle a particular gateway having limits on the content of a field.

For example, the \Omnipay\Common\Item::setDescription() does not impose a length limit. Obviously different gateways will have requirements to be matched (not just limited to description length, but maybe format, value ranges, etc.).

So, say you have a driver which has ...

```
    /**
     * @param string $value Max length of 5.
     * @return $this
     */
    public function setLanguage($value)
    {
        return parent::setLanguage(substr($value, 0, 5));
    }
```

This code works just fine. But unit test \Omnipay\Tests\GatewayTestCase::testPurchaseParameters() now fails as "Failed asserting that two strings are identical."

For the driver I'm working with, the gateway limits the language to 5 characters (as well as other limits on the values and lengths of properties of \Omnipay\Common\Item. The only option that makes sense is to use ``substr($value, 0, 5);`` in my driver. As our code base supports multiple payment gateways, we can't realistically code all the rules into our app - that's what OmniPay is for.

So, I think the testing of default parameters in this test (and potentially other tests in the common package) may not work correctly in all instances for all drivers.

One suggestion was to use the getter() as the guard, but that doesn't alter the external behaviour/view in any way, just an internal one.

I don't know the answer, so if anyone has any good ideas/suggestions/recommendations, I'd be happy to contribute code.

**Comment by barryvdh** [comment]
Imho, if the gateway is expected to give max 5 characters, the tests for that gateway should verify that the output is truncated.

**Comment by judgej** [comment]
Can the generic tests (matching up all the setters and getters) be modified to disable certain tests for a given gateway?

I suspect the approach to use here will be to not truncate the getter (and this is what the generic tests are kind of telling us to do), but to truncate at the point the message is being constructed from the data the getter supplies.

**Comment by barryvdh** [comment]
The generic tests aren't always run for custom gateways, or are they? I usually write my own tests for the code in the custom gateway, so if I override the setDescription method, I add a test for it (with my behavior) to get 100% coverage, but no need to test the abstract gateway code itself, as that is already tested by the common package.

**Comment by rquadling** [comment]
The code I'm working with does extend the common gateway test for the gateway. I think that is the first issue.

The second issue I think I'm up against is that a gateway doesn't seem to be able to advertise its own Item class. So the actual setters I've just been amending never actually get called. I had assumed some sort of autowiring was in play.

So. I think this whole issue is PICNIC. I also wonder if I'm one of the few devs that works on an app that supports multiple payment gateways (25 so far and more get added each year).

If no one has any additional comments, then I think this can be closed.

Thank you for your input.

**Comment by judgej** [comment]
If you are extending the common gateway tests, then you can probably override any tests that fail due to the truncation.

**Comment by rquadling** [comment]
@judgej Fair point. I'll be feeding this all back to the repo's owner.

**Comment by judgej** [comment]
The "family member" relationship is in contacts_contacts_c and this is an example of the two-way records that are created:

~~~csv
# id, date_modified, deleted, contacts_c95d0ontacts_ida, contacts_c902bontacts_idb
'7fa3806e-3d2d-fa3e-652e-57559fea983b', '2016-06-06 16:07:14', '0', '63da08ad-2722-ecbc-3e64-5655bf98726b', 'b7397a19-b6e9-0610-2672-530f3cbd38ad'
'8fc32c96-4345-2dca-d923-57559fdd757a', '2016-06-06 16:07:14', '0', 'b7397a19-b6e9-0610-2672-530f3cbd38ad', '63da08ad-2722-ecbc-3e64-5655bf98726b'
~~~
